;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        counsel-M-x
        delete-horizontal-space
        haskell-indentation-common-electric-command
        kill-region
        markdown-outdent-or-delete
        org-self-insert-command
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        mac-mwheel-scroll
        ))
